from textgrid_tools_cli.grid.audio_synchronization import get_audio_synchronization_parser
from textgrid_tools_cli.grid.creation import get_creation_parser
from textgrid_tools_cli.grid.splitting import get_splitting_parser
from textgrid_tools_cli.grid.stats_generation import get_stats_generation_parser
