from textgrid_tools_cli.tiers.marks_mapping import get_marks_mapping_parser
from textgrid_tools_cli.tiers.removing import get_removing_parser
from textgrid_tools_cli.tiers.silence_labeling import get_label_silence_parser
from textgrid_tools_cli.tiers.symbol_removing import get_symbol_removing_parser
from textgrid_tools_cli.tiers.transcription import get_transcription_parser
